module.exports={
  registrationService:require('./registration-service'),
  loginService:require('./login-service'),
  forgetService:require('./forgetpass-service'),
  cardService:require('./card-service'),
  userInfoService:require('./userInfo-service'),
  stationService:require('./station-service'),
  calculateFareService:require('./calculatefare-service'),
  payFareService:require('./payFare-service'),
  busService:require('./bus-service'),
  AirplaneService:require('./airplane-service'),
  launchService:require('./launch-service'),
  metroService:require('./metro-service'),
  QRservice:require('./qr-service')
}