module.exports={
  registrationService:require('./registration-service'),
  loginService:require('./login-service'),
  cardService:require('./card-service'),
  userInfoService:require('./userInfo-service'),
  stationService:require('./station-service'),
  calculateFareService:require('./calculatefare-service'),
  payFareService:require('./payFare-service'),
  busService:require('./bus-service'),
  AirplaneService:require('./airplane-service')
}